"""
agents/scope_classifier.py
==========================
Scope Classifier — Step 0 of the NIKKO pipeline.

Spec source  : SPEC-200 §5.0, REQ-200-SC1 through REQ-200-SC6
               REQ-700-SC1 through REQ-700-SC3
Phase        : 3 — Agent Definitions (Implementation)
Authority    : HIGH — OUT_OF_SCOPE is final and cannot be overridden downstream.

Role
----
Decides whether a user message falls within Nikko's operational domain
*before* any other agent runs. If it is clearly out-of-scope, the pipeline
terminates here and a static warm-redirect is returned. If in doubt, the
classifier MUST pass the message through (AMBIGUOUS → Signal Agent).

Implementation strategy — why rule-based, not a model?
-------------------------------------------------------
The spec permits "DistilBERT-class OR equivalent rule-based approach".
A fine-tuned DistilBERT will be swapped in once Phase 4 produces a
labelled dataset. For now, a weighted keyword scorer gives us:
  - Sub-millisecond latency (well inside the 500 ms ceiling, REQ-700-SC2)
  - Deterministic, auditable decisions (no stochastic LLM drift)
  - Full testability without GPU or model downloads
  - An easy drop-in point: replace `_score_rule_based()` with a model call

The class exposes a single public method — `classify()` — which returns
a validated ScopeClassifierDecision. Everything else is private.
"""

from __future__ import annotations

import re
import time
from typing import Optional

# [CONCEPT] Importing from docs.schemas
# The Phase 2 schema contracts live in docs/schemas/. We import from there
# directly. In production the package will be installed properly; during
# Phase 3 development, ensure the repo root is on sys.path (the notebook
# does this automatically).
from docs.schemas.acp_schemas import ScopeClassifierDecision, ScopeDecision
from docs.schemas.validate import get_confidence_band

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Warm redirect copy — verbatim from agent_prompts.md §1.1 (REQ-200-SC4/SC5).
# This string is STATIC. It MUST NOT be generated by an LLM or varied per user.
# If the copy changes, update it here AND in agent_prompts.md, then create a
# new REQ-ID to track the change.
WARM_REDIRECT: str = (
    "Nikko is here to support your emotional wellbeing — it sounds like that "
    "might not be what you're looking for right now. "
    "If something's weighing on you, I'm here."
)

# Confidence threshold below which we MUST return AMBIGUOUS, never OUT_OF_SCOPE.
# Locked to the SPEC-100 low-band ceiling. (REQ-200-SC3, REQ-100-CB1)
_LOW_BAND_CEILING: float = 0.40

# Minimum net score required to call OUT_OF_SCOPE with confidence >= 0.40.
# Tuned conservatively so borderline cases fall into AMBIGUOUS. (G-SCOPE-01)
_OUT_OF_SCOPE_THRESHOLD: float = 0.55


# ---------------------------------------------------------------------------
# Weighted pattern sets
# ---------------------------------------------------------------------------
# Each entry is (compiled_regex, weight). Weights are positive floats; they
# are summed and normalised to [0.0, 1.0] inside `_score_rule_based()`.
#
# Design note — why weights instead of binary flags?
# Some patterns are strong signals (e.g. "write a function" → clearly code)
# while others are weak (e.g. "explain" could be in- or out-of-scope).
# Weights let us express that nuance without a model. A single strong hit
# can clear the threshold on its own; multiple weak hits add up.

# [CONCEPT] re.compile() at module load time
# Compiling regexes once at import is a standard optimisation: the compiled
# pattern object is reused across every call to classify(). Compiling inside
# the hot path would re-parse the regex string on every request — wasteful.

_OUT_OF_SCOPE_PATTERNS: list[tuple[re.Pattern, float]] = [
    # --- Code / programming ---
    (re.compile(r"\b(write|debug|fix|implement|refactor)\s+(a\s+)?(function|class|script|program|code|module|api|algorithm|query|sql|loop)\b", re.I), 0.90),
    (re.compile(r"\b(python|javascript|typescript|java|c\+\+|rust|golang|bash|html|css|json|yaml|xml)\b", re.I), 0.70),
    (re.compile(r"(def |import |from .+ import|#include|console\.log|print\(|var |let |const )", re.I), 0.95),
    (re.compile(r"\b(syntax error|stack overflow|null pointer|compile|runtime error|unit test|docker|kubernetes|git (push|pull|merge|commit))\b", re.I), 0.85),

    # --- Mathematics / engineering ---
    (re.compile(r"\b(solve|calculate|compute|derive|integrate|differentiate)\s+(the\s+)?(equation|formula|integral|derivative|matrix|polynomial)\b", re.I), 0.85),
    (re.compile(r"[=+\-*/^]{2,}|∑|∫|√|∂|∇|\d+\s*[+\-*/^]\s*\d+\s*=", re.I), 0.80),

    # --- Recipes / food ---
    (re.compile(r"\b(recipe|ingredient|tablespoon|teaspoon|bake|fry|simmer|preheat|oven|degrees (celsius|fahrenheit))\b", re.I), 0.85),

    # --- General knowledge / trivia ---
    (re.compile(r"\b(what is the capital of|who invented|when was .+ born|how many (countries|planets|continents)|what year did)\b", re.I), 0.80),
    (re.compile(r"\b(weather forecast|stock price|exchange rate|sports score|movie showtimes|book recommendation)\b", re.I), 0.75),

    # --- Medical diagnosis / legal / financial advice ---
    (re.compile(r"\b(diagnose|prescribe|dosage|medication|symptoms of .+ disease|legal advice|file a lawsuit|tax return|invest in|portfolio)\b", re.I), 0.70),
    # Note: these overlap with mental health topics — weight kept moderate (0.70)
    # so emotional context in the same message can still pull toward IN_SCOPE.

    # --- Pure creative writing (non-emotional) ---
    (re.compile(r"\b(write (me )?(a )?(poem|story|essay|novel|script|blog post|cover letter|resume) about (?!my feelings|my anxiety|my depression|how i feel))\b", re.I), 0.75),
]

_IN_SCOPE_PATTERNS: list[tuple[re.Pattern, float]] = [
    # --- Explicit distress / emotional language ---
    (re.compile(r"\b(i('m| am) (feeling|struggling|overwhelmed|depressed|anxious|scared|hopeless|numb|exhausted|breaking down|falling apart))\b", re.I), 0.95),
    (re.compile(r"\b(i (don't|can't|couldn't) (cope|sleep|eat|go on|do (it|this) anymore))\b", re.I), 0.95),
    (re.compile(r"\b(want to (die|disappear|end it|hurt myself|not exist|give up))\b", re.I), 1.00),  # crisis signal — always in scope
    (re.compile(r"\b(suicid|self.harm|self.injur)\b", re.I), 1.00),

    # --- Relational / mental health topics ---
    (re.compile(r"\b(mental health|therapy|therapist|counselling|counseling|psychologist|psychiatrist|burnout|trauma|grief|loss|loneliness|isolation)\b", re.I), 0.85),
    (re.compile(r"\b(relationship|breakup|divorce|family (issue|conflict|problem)|domestic|abuse|partner|friend|colleague).{0,40}(stress|difficult|hurt|upset|angry|sad)\b", re.I), 0.80),

    # --- Mood and emotion words ---
    (re.compile(r"\b(sad|depressed|anxious|angry|scared|afraid|hopeless|helpless|worthless|lonely|empty|numb|ashamed|guilty|overwhelmed)\b", re.I), 0.65),
    (re.compile(r"\b(i feel|i've been feeling|feeling (like|that)|my mood|my anxiety|my depression)\b", re.I), 0.75),

    # --- Help-seeking language ---
    (re.compile(r"\b(need (help|support|someone to talk to)|don't know what to do|don't know where to turn|no one (understands|listens|cares))\b", re.I), 0.85),
    (re.compile(r"\b(can you help me|i need advice|i need to talk)\b", re.I), 0.50),  # weak signal — could be off-topic

    # --- Coping / wellbeing topics ---
    (re.compile(r"\b(coping (strategy|strategies|with|mechanism)|mindfulness|meditation|breathing (exercise|technique)|panic attack|anxiety attack)\b", re.I), 0.80),
    (re.compile(r"\b(sleep (problems?|issues?|disorder)|insomnia|nightmare|intrusive thought|rumination|negative thought)\b", re.I), 0.75),

    # --- Ambiguous-but-plausible distress surface forms (AMBIGUOUS bias) ---
    # These are weak signals that alone wouldn't classify IN_SCOPE confidently,
    # but they tip ambiguous inputs away from OUT_OF_SCOPE.
    (re.compile(r"\b(i don't know (what|where|how|why)|i can't (figure|understand|deal)|everything is (hard|difficult|too much))\b", re.I), 0.45),
    (re.compile(r"\b(stressed|stress(ful|ed)|pressure|burnt? out|tired of|fed up|can't take)\b", re.I), 0.55),
]


# ---------------------------------------------------------------------------
# Scorer
# ---------------------------------------------------------------------------

def _score_rule_based(text: str) -> tuple[float, float]:
    """
    Compute raw in-scope and out-of-scope scores for the given text.

    Returns:
        (in_scope_score, out_of_scope_score) — both in [0.0, 1.0].

    How scoring works:
    1. For each pattern set, sum the weights of all matching patterns.
    2. Cap the sum at the maximum possible weight for that set.
    3. Normalise to [0.0, 1.0] by dividing by the max-weight sum.

    Capping prevents a message that matches many weak out-of-scope patterns
    from overwhelming a single strong in-scope signal (e.g. a message about
    Python that also mentions anxiety).
    """
    def score_set(patterns: list[tuple[re.Pattern, float]]) -> float:
        total_weight = sum(w for _, w in patterns)
        hit_weight   = sum(w for pat, w in patterns if pat.search(text))
        if total_weight == 0:
            return 0.0
        # Normalise — but clamp to 1.0 in case hits exceed the theoretical max
        # (shouldn't happen, but defensive coding for future pattern additions)
        return min(hit_weight / total_weight, 1.0)

    in_score  = score_set(_IN_SCOPE_PATTERNS)
    out_score = score_set(_OUT_OF_SCOPE_PATTERNS)
    return in_score, out_score


# ---------------------------------------------------------------------------
# Classifier
# ---------------------------------------------------------------------------

class ScopeClassifier:
    """
    Lightweight scope gate — Step 0 of the NIKKO pipeline.

    This class is stateless: `classify()` takes text in, returns a decision.
    No session state is stored. Safe to call concurrently.

    Future swap-in point:
        To replace the rule-based scorer with a DistilBERT model, override
        `_compute_scores()` in a subclass (or inject a scorer callable).
        The rest of the logic — asymmetric error policy, warm redirect,
        ScopeClassifierDecision construction — stays unchanged.
    """

    def classify(self, sanitized_input: str) -> ScopeClassifierDecision:
        """
        Classify a sanitized user message and return a structured decision.

        The OUT_OF_SCOPE path MUST complete in ≤ 500 ms. (REQ-700-SC2)
        Rule-based scoring typically completes in < 1 ms.

        Args:
            sanitized_input: User message after input sanitization
                             (prompt-injection patterns stripped by pipeline).
                             MUST NOT be raw user text.

        Returns:
            ScopeClassifierDecision — validated Pydantic model.
            Pydantic will raise ValidationError if invariants are violated
            (e.g. OUT_OF_SCOPE without a warm_redirect). This is intentional
            — it means a bug in this function, not a user error.

        Raises:
            ValidationError: If the decision violates a schema invariant
                             (REQ-200-SC4, REQ-200-SC3).
        """
        start = time.perf_counter()

        decision, confidence = self._compute_decision(sanitized_input)
        warm_redirect: Optional[str] = WARM_REDIRECT if decision == ScopeDecision.OUT_OF_SCOPE else None

        elapsed_ms = (time.perf_counter() - start) * 1000

        # Latency guard — log a warning if we approach the ceiling.
        # (In production this would write to the structured logger.)
        if elapsed_ms > 400:
            print(
                f"[ScopeClassifier] WARNING: classification took {elapsed_ms:.1f} ms "
                f"— approaching the 500 ms ceiling (REQ-700-SC2)."
            )

        # [CONCEPT] Pydantic validation as a correctness gate
        # We let Pydantic validate the output rather than writing our own
        # assert statements. The model validators in ScopeClassifierDecision
        # enforce REQ-200-SC3 (low confidence → not OUT_OF_SCOPE) and
        # REQ-200-SC4 (OUT_OF_SCOPE requires warm_redirect). If either fires,
        # it means a bug in _compute_decision — surface it immediately.
        return ScopeClassifierDecision(
            decision=decision,
            confidence=confidence,
            warm_redirect=warm_redirect,
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _compute_decision(self, text: str) -> tuple[ScopeDecision, float]:
        """
        Apply rule-based scoring and the asymmetric error policy to produce
        a (decision, confidence) pair.

        Decision logic:
        1. Score the text against IN_SCOPE and OUT_OF_SCOPE pattern sets.
        2. Compute net confidence in each direction.
        3. Apply asymmetric error policy: if confidence < 0.40 → AMBIGUOUS.
        4. If out-of-scope score dominates and clears the threshold → OUT_OF_SCOPE.
        5. If in-scope score dominates → IN_SCOPE.
        6. Otherwise → AMBIGUOUS.

        The asymmetric policy (step 3) is the most important rule in this
        function. It encodes the spec's safety principle: rejecting a
        distress-coded message is a safety failure; passing an off-topic
        message through is merely inefficient. (REQ-200-SC3)
        """
        in_score, out_score = _score_rule_based(text)

        # --- Case 1: Strong in-scope signal ---
        # In-scope beats out-of-scope AND clears the low-band ceiling.
        if in_score > out_score and in_score >= _LOW_BAND_CEILING:
            confidence = self._blend_confidence(in_score, out_score)
            return ScopeDecision.IN_SCOPE, confidence

        # --- Case 2: Strong out-of-scope signal ---
        # Out-of-scope dominates AND clears a conservative threshold.
        # We do NOT allow OUT_OF_SCOPE if confidence < 0.40 — the asymmetric
        # policy is enforced here (and again by Pydantic as a safety net).
        if out_score > in_score and out_score >= _OUT_OF_SCOPE_THRESHOLD:
            confidence = self._blend_confidence(out_score, in_score)
            # Asymmetric guard: if confidence dropped into the low band,
            # override to AMBIGUOUS even though the pattern score looked strong.
            # (REQ-200-SC3) — Pydantic would catch this too, but we prefer to
            # be explicit so the validator is a last-resort guard, not primary logic.
            if confidence < _LOW_BAND_CEILING:
                return ScopeDecision.AMBIGUOUS, confidence
            return ScopeDecision.OUT_OF_SCOPE, confidence

        # --- Case 3: No clear signal — AMBIGUOUS ---
        # Both scores are low, or they're too close to call.
        # AMBIGUOUS routes to the Signal Agent, which can perform deeper analysis.
        # This is the correct safe default. (REQ-200-SC3)
        ambiguous_confidence = max(in_score, out_score, 0.20)  # floor at 0.20 to avoid 0.0
        return ScopeDecision.AMBIGUOUS, min(ambiguous_confidence, _LOW_BAND_CEILING - 0.01)

    @staticmethod
    def _blend_confidence(dominant_score: float, competing_score: float) -> float:
        """
        Convert raw pattern scores into a calibrated confidence value.

        Formula: dominant * (1 - 0.5 * competing)
        - When the competing score is zero, confidence equals the dominant score.
        - A strong competing signal reduces confidence proportionally.
        - Result is always in [0.0, 1.0].

        This is a simple heuristic, not a calibrated probability. It is
        good enough for the rule-based phase and will be replaced by the
        model's own softmax output when DistilBERT is integrated.
        """
        return dominant_score * (1.0 - 0.5 * competing_score)
