"""
agents/scope_classifier.py
==========================
Scope Classifier — Step 0 of the NIKKO pipeline.

Spec source  : SPEC-200 §5.0, REQ-200-SC1 through REQ-200-SC6
               REQ-700-SC1 through REQ-700-SC3
Phase        : 3 — Agent Definitions (Implementation)
Authority    : HIGH — OUT_OF_SCOPE is final and cannot be overridden downstream.

Role
----
Decides whether a user message falls within Nikko's operational domain
*before* any other agent runs. If it is clearly out-of-scope, the pipeline
terminates here and a static warm-redirect is returned. If in doubt, the
classifier MUST pass the message through (AMBIGUOUS → Signal Agent).

Implementation strategy — why rule-based, not a model?
-------------------------------------------------------
The spec permits "DistilBERT-class OR equivalent rule-based approach".
A fine-tuned DistilBERT will be swapped in once Phase 4 produces a
labelled dataset. For now, a weighted keyword scorer gives us:
  - Sub-millisecond latency (well inside the 500 ms ceiling, REQ-700-SC2)
  - Deterministic, auditable decisions (no stochastic LLM drift)
  - Full testability without GPU or model downloads
  - An easy drop-in point: replace `_score_rule_based()` with a model call

The class exposes a single public method — `classify()` — which returns
a validated ScopeClassifierDecision. Everything else is private.
"""

from __future__ import annotations

import re
import time
from typing import Optional

# [CONCEPT] Importing from docs.schemas
# The Phase 2 schema contracts live in docs/schemas/. We import from there
# directly. In production the package will be installed properly; during
# Phase 3 development, ensure the repo root is on sys.path (the notebook
# does this automatically).
from docs.schemas.acp_schemas import ScopeClassifierDecision, ScopeDecision
from docs.schemas.validate import get_confidence_band

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Warm redirect copy — verbatim from agent_prompts.md §1.1 (REQ-200-SC4/SC5).
# This string is STATIC. It MUST NOT be generated by an LLM or varied per user.
# If the copy changes, update it here AND in agent_prompts.md, then create a
# new REQ-ID to track the change.
WARM_REDIRECT: str = (
    "That's a bit outside what I'm set up for — Nikko is here for emotional "
    "wellbeing and mental health support. If something's been on your mind "
    "or weighing on you, I'm here for that."
)

# Confidence threshold below which we MUST return AMBIGUOUS, never OUT_OF_SCOPE.
# Locked to the SPEC-100 low-band ceiling. (REQ-200-SC3, REQ-100-CB1)
_LOW_BAND_CEILING: float = 0.40

# Minimum net score required to call OUT_OF_SCOPE with confidence >= 0.40.
# Tuned conservatively so borderline cases fall into AMBIGUOUS. (G-SCOPE-01)
_OUT_OF_SCOPE_THRESHOLD: float = 0.55


# ---------------------------------------------------------------------------
# Weighted pattern sets
# ---------------------------------------------------------------------------
# Each entry is (compiled_regex, weight). Weights are positive floats; they
# are summed and normalised to [0.0, 1.0] inside `_score_rule_based()`.
#
# Design note — why weights instead of binary flags?
# Some patterns are strong signals (e.g. "write a function" → clearly code)
# while others are weak (e.g. "explain" could be in- or out-of-scope).
# Weights let us express that nuance without a model. A single strong hit
# can clear the threshold on its own; multiple weak hits add up.

# [CONCEPT] re.compile() at module load time
# Compiling regexes once at import is a standard optimisation: the compiled
# pattern object is reused across every call to classify(). Compiling inside
# the hot path would re-parse the regex string on every request — wasteful.

# [CONCEPT] Vocabulary alignment with TopicTag taxonomy (G-RETRIEVAL-02)
# The keyword lists below serve a different purpose to the retrieval layer's
# _TOPIC_KEYWORDS in retrieval/web_search_adapter.py, but both operate on the
# same mental-health vocabulary. If you add a new clinical concept to the
# TopicTag taxonomy or update topic keyword lists in web_search_adapter.py,
# review the in-scope patterns here to ensure the scope gate still passes
# those messages through to the Signal Agent. The two files are intentionally
# independent (scope gate fires before retrieval; they must never share state)
# but should stay conceptually consistent. Key overlaps to watch:
#   CRISIS keywords   ↔  crisis/suicid/self-harm patterns (weight 1.00 below)
#   GRIEF keywords    ↔  "grief", "loss", "bereavem" in _IN_SCOPE_PATTERNS
#   YOUTH keywords    ↔  "young", "teen", "school" in _IN_SCOPE_PATTERNS (via mental health)
#   INDIGENOUS kws    ↔  not currently in scope patterns — add if AU context warrants
#   TRAUMA keywords   ↔  "trauma" in _IN_SCOPE_PATTERNS (relational/mental health)

_OUT_OF_SCOPE_PATTERNS: list[tuple[re.Pattern, float]] = [
    # --- Code / programming ---
    # Extended verb list: code, build, create, develop, make (REQ-200-SC2).
    # Extended object list: website, app, game, dashboard, ui, frontend, backend.
    (re.compile(r"\b(write|debug|fix|implement|refactor|code|build|create|develop|make)\s+(a\s+|me\s+a\s+)?(function|class|script|program|code|module|api|algorithm|query|sql|loop|website|web\s*app|application|game|dashboard|ui|frontend|backend|webpage|landing\s*page)\b", re.I), 0.90),
    # Help-framed coding intent — catches "can you help me code a website",
    # "help me build an app" etc. that use generic help framing + a coding verb.
    # Weight 0.85: strong enough to dominate even if "can you help me" fires on
    # the in-scope side (0.50); blend formula still resolves to OUT_OF_SCOPE.
    (re.compile(r"\b(help me|could you|can you)\s+(code|build|create|develop|make|write)\s+(a\s+)?(website|web\s*app|application|app|game|dashboard|ui|frontend|backend|webpage|script|program|function)\b", re.I), 0.85),
    (re.compile(r"\b(python|javascript|typescript|java|c\+\+|rust|golang|bash|html|css|json|yaml|xml)\b", re.I), 0.70),
    (re.compile(r"(def |import |from .+ import|#include|console\.log|print\(|var |let |const )", re.I), 0.95),
    (re.compile(r"\b(syntax error|stack overflow|null pointer|compile|runtime error|unit test|docker|kubernetes|git (push|pull|merge|commit))\b", re.I), 0.85),

    # --- Mathematics / engineering ---
    (re.compile(r"\b(solve|calculate|compute|derive|integrate|differentiate)\s+(the\s+)?(equation|formula|integral|derivative|matrix|polynomial)\b", re.I), 0.85),
    (re.compile(r"[=+\-*/^]{2,}|∑|∫|√|∂|∇|\d+\s*[+\-*/^]\s*\d+\s*=", re.I), 0.80),

    # --- Recipes / food ---
    (re.compile(r"\b(recipe|ingredient|tablespoon|teaspoon|bake|fry|simmer|preheat|oven|degrees (celsius|fahrenheit))\b", re.I), 0.85),

    # --- General knowledge / trivia ---
    # Bug fix: handle "what's" contraction alongside "what is" (REQ-200-SC2).
    (re.compile(r"\b(what(?:'s| is) the capital of|who invented|when was .+ born|how many (countries|planets|continents)|what year did)\b", re.I), 0.80),
    (re.compile(r"\b(weather forecast|stock price|exchange rate|sports score|movie showtimes|book recommendation)\b", re.I), 0.75),

    # --- Medical diagnosis / legal / financial advice ---
    (re.compile(r"\b(diagnose|prescribe|dosage|medication|symptoms of .+ disease|legal advice|file a lawsuit|tax return|invest in|portfolio)\b", re.I), 0.70),
    # Note: these overlap with mental health topics — weight kept moderate (0.70)
    # so emotional context in the same message can still pull toward IN_SCOPE.

    # --- Pure creative writing (non-emotional) ---
    (re.compile(r"\b(write (me )?(a )?(poem|story|essay|novel|script|blog post|cover letter|resume) about (?!my feelings|my anxiety|my depression|how i feel))\b", re.I), 0.75),

    # --- Physical health (non-mental) ---
    # Routes physical health complaints to the GP/specialist redirect.
    # Weights are kept moderate (0.75–0.80) so physical symptoms mentioned
    # alongside emotional distress still pass through via the asymmetric
    # error policy — e.g. "my back pain is making me really depressed"
    # scores IN_SCOPE (0.90 for "depressed") >> OUT_OF_SCOPE (0.80 for
    # back pain), routing correctly to the pipeline. Only isolated physical
    # health queries with no emotional language get redirected.
    # Exclusions: psychological conditions (anxiety, depression, PTSD, OCD,
    # ADHD, etc.) are deliberately absent — they are IN_SCOPE mental health.
    (re.compile(r"\b(my\s+)?(back|neck|knee|shoulder|hip|wrist|ankle|elbow|spine|disc|joint)\s+(pain|ache|aches|hurts?|problems?|issues?|injury|injuries|condition|spasm|spasms)\b", re.I), 0.80),
    (re.compile(r"\b(my\s+)?(stomach|chest|throat|ear|tooth|teeth|eye|nose|head)\s+(hurts?|is\s+sore|is\s+aching|ache|pain)\b", re.I), 0.75),
    (re.compile(r"\b(i\s+(have|had|got|'?ve\s+(got|had))|been\s+diagnosed\s+with)\s+(chronic\s+)?(back\s+pain|neck\s+pain|sciatica|arthritis|fibromyalgia|diabetes|cancer|hypertension|high\s+blood\s+pressure|asthma|epilepsy|IBS|Crohn'?s?|colitis|GERD|acid\s+reflux|kidney\s+(disease|stones)|liver\s+(disease|problems?)|heart\s+(disease|condition|problems?)|a\s+hernia|tendinitis|bursitis)\b", re.I), 0.80),
    (re.compile(r"\bi\s+(have|had|got)\s+(a\s+)?(cold|flu|fever|fracture|broken\s+(bone|arm|leg|rib)|sprain|pulled\s+muscle|concussion|food\s+poisoning|infection|rash|uti|urinary\s+tract)\b", re.I), 0.80),
    (re.compile(r"\b(what\s+medication|which\s+doctor|should\s+I\s+see\s+a\s+(doctor|specialist|gp|physio)|do\s+I\s+need\s+(surgery|an?\s+x.?ray|a\s+(scan|referral)|antibiotics|stitches))\b", re.I), 0.75),

    # --- Current affairs / political opinion requests ---
    # Important design note: these patterns target INFORMATION REQUESTS and
    # OPINION-SEEKING about politics/current events — not emotional responses
    # to those events. "I'm anxious about the election" scores strongly on
    # IN_SCOPE emotional patterns and will still pass through even with these
    # weights (asymmetric error policy, REQ-200-SC3). What gets blocked is:
    # "tell me about the news today", "who should I vote for", "what's your
    # take on abortion", etc. — information/debate requests that Nikko cannot
    # and should not engage with as a mental health support tool.
    (re.compile(r"\b(latest|breaking|current)\s+(news|headlines|events)\b", re.I), 0.80),
    (re.compile(r"\b(what('s|is)\s+(happening|going\s+on)\s+(in\s+the\s+(world|country)|with\s+(politics|the\s+government)))\b", re.I), 0.80),
    (re.compile(r"\b(who\s+should\s+(i|we)\s+vote\s+for|which\s+(party|candidate)\s+(is|are)\s+better)\b", re.I), 0.90),
    (re.compile(r"\b(what('s|is)\s+your\s+(opinion|view|take|stance|position)\s+on\s+(abortion|immigration|gun\s+control|climate\s+change|vaccines?|tax(ation)?|politics|the\s+election))\b", re.I), 0.85),
    (re.compile(r"\b(is\s+(abortion|immigration|the\s+death\s+penalty|euthanasia)\s+(right|wrong|legal|moral|ethical|okay|ok))\b", re.I), 0.80),
    (re.compile(r"\b(tell\s+me\s+(about|why)\s+(donald\s+trump|joe\s+biden|labour\s+party|the\s+tories|the\s+liberals|the\s+republicans|the\s+democrats))\b", re.I), 0.85),
    (re.compile(r"\b(what\s+do\s+you\s+think\s+about\s+(the\s+(government|election|president|prime\s+minister|war|conflict|protest)))\b", re.I), 0.85),
    (re.compile(r"\b(summarise?|explain|what\s+happened\s+with)\s+(the\s+)?(war\s+in|conflict\s+in|situation\s+in)\s+\w+\b", re.I), 0.75),
]

_IN_SCOPE_PATTERNS: list[tuple[re.Pattern, float]] = [
    # --- Crisis-tier signals (weight 1.00) — MUST always pass through ---
    # Any match here makes the input unambiguously in-scope.
    # Note: no trailing \b after incomplete stems like "suicid" — "suicidal",
    # "suicidality", "suicide" all need to match. Same for "self.harm\w*".
    (re.compile(r"\b(want to (die|disappear|end it|hurt myself|not exist|give up))\b", re.I), 1.00),
    (re.compile(r"\b(kill(ing)? (myself|oneself)|end(ing)? my life|take my (own )?life)\b", re.I), 1.00),
    (re.compile(r"\b(thinking about (ending|suicide|killing|hurting)|plan(ning)? to (end|kill|hurt))\b", re.I), 1.00),
    (re.compile(r"\bsuicid\w*\b", re.I), 1.00),  # suicide, suicidal, suicidality
    (re.compile(r"\bself[.\-\s]harm\w*\b", re.I), 1.00),
    (re.compile(r"\bself[.\-\s]injur\w*\b", re.I), 1.00),
    # Farewell framing — indirect but high-risk (REQ-100-060, risk.passive tier)
    (re.compile(r"\b(said goodbye|saying goodbye|wrote a (note|letter)|gave away my)\b", re.I), 0.90),
    (re.compile(r"\b(do not want to exist|don'?t want to (be here|exist|be alive))\b", re.I), 1.00),

    # --- Explicit distress / emotional language ---
    # Broad subject match: "I'm", "I am", "I have been", "I keep", "I cannot"
    (re.compile(r"\bi (am|'m|have been|keep|cannot|can'?t) (feeling|struggling|crying|shaking|breaking down|falling apart)\b", re.I), 0.95),
    (re.compile(r"\bi (am|'m|have been) (feeling )?(really |so )?(low|lost|hopeless|empty|numb|broken|overwhelmed|exhausted|depressed|anxious)\b", re.I), 0.90),
    (re.compile(r"\bi (don'?t|can'?t|couldn'?t) (cope|sleep|eat|go on|do (it|this) anymore|stop (crying|thinking))\b", re.I), 0.95),
    (re.compile(r"\bcannot stop (crying|thinking|feeling)\b", re.I), 0.90),

    # --- Relational / mental health topics ---
    (re.compile(r"\b(mental health|therapy|therapist|counselling|counseling|psychologist|psychiatrist|burnout|trauma|grief|loss|loneliness|isolation)\b", re.I), 0.85),
    (re.compile(r"\b(relationship|breakup|divorce|family (issue|conflict|problem)|domestic|abuse|partner|friend|colleague).{0,40}(stress|difficult|hurt|upset|angry|sad)\b", re.I), 0.80),

    # --- Mood and emotion words ---
    (re.compile(r"\b(sad|depressed|anxious|angry|scared|afraid|hopeless|helpless|worthless|lonely|empty|numb|ashamed|guilty|overwhelmed)\b", re.I), 0.65),
    (re.compile(r"\b(i feel|i'?ve been feeling|feeling (like|that)|my mood|my anxiety|my depression)\b", re.I), 0.75),

    # --- Help-seeking language ---
    (re.compile(r"\b(need (help|support|someone to talk to)|don'?t know what to do|don'?t know where to turn|no one (understands|listens|cares))\b", re.I), 0.85),
    # "i need advice / i need to talk" are specific support-seeking phrases — keep at 0.50.
    # "can you help me" is too generic alone to clear the 0.40 IN_SCOPE threshold;
    # weight reduced to 0.30 so it lands AMBIGUOUS without other emotional context.
    # This prevents "can you help me code a website" from winning on in_scope alone
    # even before the new compound out-of-scope pattern fires. (Bug fix, REQ-200-SC3)
    (re.compile(r"\b(i need advice|i need to talk)\b", re.I), 0.50),
    (re.compile(r"\bcan you help me\b", re.I), 0.30),

    # --- Coping / wellbeing topics ---
    # "panic attacks?" — trailing s? makes the plural match too
    (re.compile(r"\b(coping (strategy|strategies|with|mechanism)|mindfulness|meditation|breathing (exercise|technique)|panic attacks?|anxiety attacks?)\b", re.I), 0.80),
    (re.compile(r"\b(sleep (problems?|issues?|disorder)|insomnia|nightmare|intrusive thought|rumination|negative thought)\b", re.I), 0.75),

    # --- Ambiguous-but-plausible distress surface forms (AMBIGUOUS bias) ---
    (re.compile(r"\b(i don'?t know (what|where|how|why)|i can'?t (figure|understand|deal)|everything is (hard|difficult|too much))\b", re.I), 0.45),
    (re.compile(r"\b(stressed|stress(ful|ed)|pressure|burnt? out|tired of|fed up|can'?t take)\b", re.I), 0.55),
]


# ---------------------------------------------------------------------------
# Scorer
# ---------------------------------------------------------------------------

def _score_rule_based(text: str) -> tuple[float, float]:
    """
    Compute raw in-scope and out-of-scope scores for the given text.

    Returns:
        (in_scope_score, out_of_scope_score) — both in [0.0, 1.0].

    How scoring works:
    1. For each pattern set, sum the weights of all matching patterns.
    2. Cap the sum at the maximum possible weight for that set.
    3. Normalise to [0.0, 1.0] by dividing by the max-weight sum.

    Capping prevents a message that matches many weak out-of-scope patterns
    from overwhelming a single strong in-scope signal (e.g. a message about
    Python that also mentions anxiety).
    """
    def score_set(patterns: list[tuple[re.Pattern, float]]) -> float:
        # Sum the weights of every matching pattern, then cap at 1.0.
        # We do NOT normalise by total_weight — that would divide each hit by
        # the sum of all pattern weights (~10-11), collapsing every score to
        # near-zero regardless of match quality. Instead, a single strong-
        # weight match (e.g. 0.95) should yield a high score on its own, and
        # multiple weaker matches should compound up to the 1.0 ceiling.
        hit_weight = sum(w for pat, w in patterns if pat.search(text))
        return min(hit_weight, 1.0)

    in_score  = score_set(_IN_SCOPE_PATTERNS)
    out_score = score_set(_OUT_OF_SCOPE_PATTERNS)
    return in_score, out_score


# ---------------------------------------------------------------------------
# Classifier
# ---------------------------------------------------------------------------

class ScopeClassifier:
    """
    Lightweight scope gate — Step 0 of the NIKKO pipeline.

    This class is stateless: `classify()` takes text in, returns a decision.
    No session state is stored. Safe to call concurrently.

    Future swap-in point:
        To replace the rule-based scorer with a DistilBERT model, override
        `_compute_scores()` in a subclass (or inject a scorer callable).
        The rest of the logic — asymmetric error policy, warm redirect,
        ScopeClassifierDecision construction — stays unchanged.
    """

    def classify(self, sanitized_input: str) -> ScopeClassifierDecision:
        """
        Classify a sanitized user message and return a structured decision.

        The OUT_OF_SCOPE path MUST complete in ≤ 500 ms. (REQ-700-SC2)
        Rule-based scoring typically completes in < 1 ms.

        Args:
            sanitized_input: User message after input sanitization
                             (prompt-injection patterns stripped by pipeline).
                             MUST NOT be raw user text.

        Returns:
            ScopeClassifierDecision — validated Pydantic model.
            Pydantic will raise ValidationError if invariants are violated
            (e.g. OUT_OF_SCOPE without a warm_redirect). This is intentional
            — it means a bug in this function, not a user error.

        Raises:
            ValidationError: If the decision violates a schema invariant
                             (REQ-200-SC4, REQ-200-SC3).
        """
        start = time.perf_counter()

        decision, confidence = self._compute_decision(sanitized_input)
        warm_redirect: Optional[str] = WARM_REDIRECT if decision == ScopeDecision.OUT_OF_SCOPE else None

        elapsed_ms = (time.perf_counter() - start) * 1000

        # Latency guard — log a warning if we approach the ceiling.
        # (In production this would write to the structured logger.)
        if elapsed_ms > 400:
            print(
                f"[ScopeClassifier] WARNING: classification took {elapsed_ms:.1f} ms "
                f"— approaching the 500 ms ceiling (REQ-700-SC2)."
            )

        # [CONCEPT] Pydantic validation as a correctness gate
        # We let Pydantic validate the output rather than writing our own
        # assert statements. The model validators in ScopeClassifierDecision
        # enforce REQ-200-SC3 (low confidence → not OUT_OF_SCOPE) and
        # REQ-200-SC4 (OUT_OF_SCOPE requires warm_redirect). If either fires,
        # it means a bug in _compute_decision — surface it immediately.
        return ScopeClassifierDecision(
            decision=decision,
            confidence=confidence,
            warm_redirect=warm_redirect,
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _compute_decision(self, text: str) -> tuple[ScopeDecision, float]:
        """
        Apply rule-based scoring and the asymmetric error policy to produce
        a (decision, confidence) pair.

        Decision logic:
        1. Score the text against IN_SCOPE and OUT_OF_SCOPE pattern sets.
        2. Compute net confidence in each direction.
        3. Apply asymmetric error policy: if confidence < 0.40 → AMBIGUOUS.
        4. If out-of-scope score dominates and clears the threshold → OUT_OF_SCOPE.
        5. If in-scope score dominates → IN_SCOPE.
        6. Otherwise → AMBIGUOUS.

        The asymmetric policy (step 3) is the most important rule in this
        function. It encodes the spec's safety principle: rejecting a
        distress-coded message is a safety failure; passing an off-topic
        message through is merely inefficient. (REQ-200-SC3)
        """
        in_score, out_score = _score_rule_based(text)

        # --- Case 1: Strong in-scope signal ---
        # In-scope beats out-of-scope AND clears the low-band ceiling.
        if in_score > out_score and in_score >= _LOW_BAND_CEILING:
            confidence = self._blend_confidence(in_score, out_score)
            return ScopeDecision.IN_SCOPE, confidence

        # --- Case 2: Strong out-of-scope signal ---
        # Out-of-scope dominates AND clears a conservative threshold.
        # We do NOT allow OUT_OF_SCOPE if confidence < 0.40 — the asymmetric
        # policy is enforced here (and again by Pydantic as a safety net).
        if out_score > in_score and out_score >= _OUT_OF_SCOPE_THRESHOLD:
            confidence = self._blend_confidence(out_score, in_score)
            # Asymmetric guard: if confidence dropped into the low band,
            # override to AMBIGUOUS even though the pattern score looked strong.
            # (REQ-200-SC3) — Pydantic would catch this too, but we prefer to
            # be explicit so the validator is a last-resort guard, not primary logic.
            if confidence < _LOW_BAND_CEILING:
                return ScopeDecision.AMBIGUOUS, confidence
            return ScopeDecision.OUT_OF_SCOPE, confidence

        # --- Case 3: No clear signal — AMBIGUOUS ---
        # Both scores are low, or they're too close to call.
        # AMBIGUOUS routes to the Signal Agent, which can perform deeper analysis.
        # This is the correct safe default. (REQ-200-SC3)
        ambiguous_confidence = max(in_score, out_score, 0.20)  # floor at 0.20 to avoid 0.0
        return ScopeDecision.AMBIGUOUS, min(ambiguous_confidence, _LOW_BAND_CEILING - 0.01)

    @staticmethod
    def _blend_confidence(dominant_score: float, competing_score: float) -> float:
        """
        Convert raw pattern scores into a calibrated confidence value.

        Formula: dominant * (1 - 0.5 * competing)
        - When the competing score is zero, confidence equals the dominant score.
        - A strong competing signal reduces confidence proportionally.
        - Result is always in [0.0, 1.0].

        This is a simple heuristic, not a calibrated probability. It is
        good enough for the rule-based phase and will be replaced by the
        model's own softmax output when DistilBERT is integrated.
        """
        return dominant_score * (1.0 - 0.5 * competing_score)
